services:
  gerrit:
    image: docker.io/gerritcodereview/gerrit:3.8.0
    container_name: gerrit
    restart: unless-stopped
    ports:
      - "8081:8080"   
      - "29418:29418" 
    volumes:
      - gerrit_data:/var/gerrit
      
    environment: {}
volumes:
  gerrit_data:
