services:
  gerrit:
    image: gerritcodereview/gerrit:3.9.1
    ports:
      - "8082:8080"
      - "29418:29418"
    volumes:
      - ./gerrit-site:/var/gerrit/review_site
    environment:
      - CANONICAL_WEB_URL=http://localhost:8082 # Gerrit이 생성하는 링크의 기준 주소 설정임, 향후 변경 필요